In [15]:
import pandas as pd 
import numpy as np 
import seaborn as sns

In [16]:
df1 = pd.read_csv('D:/Git_hub/p1/V3/Dataset_Kaggle/dataset1.csv')
print(df1.shape)
df2 = pd.read_csv('D:/Git_hub/p1/V3/Dataset_Kaggle/dataset2.csv')
print(df2.shape)
df3 = pd.read_csv('D:/Git_hub/p1/V3/Dataset_Kaggle/dataset3.csv')
print(df3.shape)

(8234, 2)
(1000, 5)
(1000, 11)

In [17]:
print(df1.columns)

print(df2.columns)

df3.columns

Index(['Resume', 'Category'], dtype='object')
Index(['candidate_id', 'skills', 'qualification', 'experience_level',
       'job_role'],
      dtype='object')

Index(['Resume_ID', 'Name', 'Skills', 'Experience (Years)', 'Education',
       'Certifications', 'Job Role', 'Recruiter Decision',
       'Salary Expectation ($)', 'Projects Count', 'AI Score (0-100)'],
      dtype='object')

In [18]:
df1.head()

                                              Resume          Category
0  Python Developer Python Developer Philadelphia...  Python_Developer
1  Python Developer Python Developer Python Devel...  Python_Developer
2  R&D Engineer R&D Engineer R&D Engineer - Nokia...  Python_Developer
3  Sr. Full Stack Developer Sr. Full Stack Develo...  Python_Developer
4  Sr. Full Stack Python Developer Sr. Full Stack...  Python_Developer

In [19]:
df1['Category'].unique()

array(['Python_Developer', 'Java_Developer', 'Front_End_Developer',
       'Network_Administrator', 'Project_manager', 'Security_Analyst',
       'Software_Developer', 'Systems_Administrator', 'Web_Developer',
       'Database_Administrator'], dtype=object)

In [20]:
df1.isnull().sum()

Resume      0
Category    0
dtype: int64

In [21]:
df2.head()

,candidate_id,skills,qualification,experience_level,job_role
0,1,"Python, SQL, TensorFlow, Machine Learning, Com...",Master's in Data Science,Senior,Data Scientist
1,2,"HTML, CSS, JavaScript, React, Teamwork",Bachelor's in Computer Science,Mid,Frontend Developer
2,3,"Java, Spring, SQL, REST APIs, Problem Solving",Bachelor's in Software Engineering,Senior,Backend Developer
3,4,"Figma, Adobe XD, UI/UX Design, Creativity",Bachelor's in Design,Entry,Designer
4,5,"Python, Django, JavaScript, React, Agile",Master's in Computer Science,Mid,Full Stack Python Developer

In [22]:
df2.isnull().sum()

candidate_id        0
skills              0
qualification       0
experience_level    0
job_role            0
dtype: int64

In [23]:
df2['job_role'].unique()

array(['Data Scientist', 'Frontend Developer', 'Backend Developer',
       'Designer', 'Full Stack Python Developer', 'Finance',
       'Game Developer', 'DevOps Engineer', 'Full Stack Java Developer',
       'Blockchain Developer', 'Marketing', 'HR', 'C# Developer',
       'PHP Developer', 'Mobile Developer', 'Cybersecurity Engineer',
       'Software Project Manager', 'Video Game Designer', 'Data Analyst',
       'Kubernetes Operations Engineer', 'Web Developer', 'AIML'],
      dtype=object)

In [25]:
df3.head()

,Resume_ID,Name,Skills,Experience (Years),Education,Certifications,Job Role,Recruiter Decision,Salary Expectation ($),Projects Count,AI Score (0-100)
0,1,Ashley Ali,"TensorFlow, NLP, Pytorch",10,B.Sc,NaN,AI Researcher,Hire,104895,8,100
1,2,Wesley Roman,"Deep Learning, Machine Learning, Python, SQL",10,MBA,Google ML,Data Scientist,Hire,113002,1,100
2,3,Corey Sanchez,"Ethical Hacking, Cybersecurity, Linux",1,MBA,Deep Learning Specialization,Cybersecurity Analyst,Hire,71766,7,70
3,4,Elizabeth Carney,"Python, Pytorch, TensorFlow",7,B.Tech,AWS Certified,AI Researcher,Hire,46848,0,95
4,5,Julie Hill,"SQL, React, Java",4,PhD,NaN,Software Engineer,Hire,87441,9,100

In [26]:
df3.isnull().sum()

Resume_ID                   0
Name                        0
Skills                      0
Experience (Years)          0
Education                   0
Certifications            274
Job Role                    0
Recruiter Decision          0
Salary Expectation ($)      0
Projects Count              0
AI Score (0-100)            0
dtype: int64

In [27]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Resume_ID               1000 non-null   int64
 1   Name                    1000 non-null   object
 2   Skills                  1000 non-null   object
 3   Experience (Years)      1000 non-null   int64
 4   Education               1000 non-null   object
 5   Certifications          726 non-null    object
 6   Job Role                1000 non-null   object
 7   Recruiter Decision      1000 non-null   object
 8   Salary Expectation ($)  1000 non-null   int64
 9   Projects Count          1000 non-null   int64
 10  AI Score (0-100)        1000 non-null   int64
dtypes: int64(5), object(6)
memory usage: 86.1+ KB

In [29]:
df3['Certifications'] = df3['Certifications'].fillna(df3['Certifications'].mode()[0])

In [30]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Resume_ID               1000 non-null   int64
 1   Name                    1000 non-null   object
 2   Skills                  1000 non-null   object
 3   Experience (Years)      1000 non-null   int64
 4   Education               1000 non-null   object
 5   Certifications          1000 non-null   object
 6   Job Role                1000 non-null   object
 7   Recruiter Decision      1000 non-null   object
 8   Salary Expectation ($)  1000 non-null   int64
 9   Projects Count          1000 non-null   int64
 10  AI Score (0-100)        1000 non-null   int64
dtypes: int64(5), object(6)
memory usage: 86.1+ KB

In [31]:
df3['Job Role'].unique()

array(['AI Researcher', 'Data Scientist', 'Cybersecurity Analyst',
       'Software Engineer'], dtype=object)

In [32]:
df1['Category'].value_counts()

Category
Python_Developer          1278
Java_Developer            1242
Web_Developer              984
Database_Administrator     920
Security_Analyst           876
Systems_Administrator      776
Project_manager            722
Front_End_Developer        530
Network_Administrator      469
Software_Developer         437
Name: count, dtype: int64

In [33]:
df2['job_role'].value_counts()

job_role
Mobile Developer                  75
Data Scientist                    50
Marketing                         50
Data Analyst                      50
Software Project Manager          50
Cybersecurity Engineer            50
PHP Developer                     50
C# Developer                      50
Frontend Developer                50
HR                                50
Blockchain Developer              50
Full Stack Java Developer         50
DevOps Engineer                   50
Game Developer                    50
Full Stack Python Developer       50
Designer                          50
Backend Developer                 50
Kubernetes Operations Engineer    49
Web Developer                     49
AIML                              25
Finance                            1
Video Game Designer                1
Name: count, dtype: int64

In [35]:
df3['Job Role'].value_counts()

Job Role
AI Researcher            257
Data Scientist           255
Cybersecurity Analyst    255
Software Engineer        233
Name: count, dtype: int64